### ISSUE TITLE
Problem restore

### ISSUE THREAD

**Issue by delmobispo** [theohbrothers/docker-imap-backup#16]
docker run --rm -it -v volume::/root/.imap-backup theohbrothers/docker-imap-backup restore email@email.com

Error:
/usr/local/bundle/gems/imap-backup-9.2.0/lib/email/mboxrd/message.rb:11:in `clean_serialized': undefined method `gsub' for nil:NilClass (NoMethodError)

      cleaned = serialized.gsub(/^>(>*From)/, "\\1")
                          ^^^^^
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/email/mboxrd/message.rb:23:in `from_serialized'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/serializer/message.rb:34:in `message'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/serializer/message.rb:39:in `body'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/uploader.rb:34:in `upload_message'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/uploader.rb:23:in `block in run'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/serializer/message_enumerator.rb:16:in `block in run'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/serializer/message_enumerator.rb:10:in `each'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/serializer/message_enumerator.rb:10:in `run'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/serializer.rb:96:in `each_message'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/uploader.rb:22:in `with_index'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/uploader.rb:22:in `run'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/account/connection.rb:93:in `block in restore'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/account/connection.rb:87:in `block in local_folders'
        from <internal:dir>:220:in `glob'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/account/connection.rb:83:in `glob'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/account/connection.rb:83:in `local_folders'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/account/connection.rb:92:in `restore'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/cli/restore.rb:21:in `run'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/cli.rb:182:in `restore'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/imap-backup-9.2.0/bin/imap-backup:12:in `block in <top (required)>'
        from /usr/local/bundle/gems/imap-backup-9.2.0/lib/imap/backup/logger.rb:39:in `sanitize_stderr'
        from /usr/local/bundle/gems/imap-backup-9.2.0/bin/imap-backup:11:in `<top (required)>'
        from /usr/local/bundle/bin/imap-backup:25:in `load'
        from /usr/local/bundle/bin/imap-backup:25:in `<main>'

**Comment by leojonathanoh** [comment]
i haven't been using `imap-backup`, not sure if this bug is related with the image, or with [`imap-backup` `9.2.0`](https://github.com/joeyates/imap-backup/releases) itself which might have had a bug. Either way, i'll build [`9.3.1`](https://github.com/joeyates/imap-backup/releases) and please once it's released, please try it, let me know if it works.

**Comment by leojonathanoh** [comment]
I've added `9.3.x` and various other older versions, please try them out, hope it works for you.

**Comment by leojonathanoh** [comment]
I've tried `imap-backup restore` on `9.3.1`, doesn't give problems so far. Perhaps you could try it.

EDIT: Tried `9.2.0`, also no problems. I'm still not sure why you are getting that error, can't seem to reproduce.

**Comment by leojonathanoh** [comment]
There's now `10.0.1` and `11.x.x` which may work better. 

I'm closing this due to inactivity. Feel free to re-open if the problem persists.
